org.gradle.jvmargs=-Xmx8G -XX:MaxMetaspaceSize=4G -XX:ReservedCodeCacheSize=512m -XX:+HeapDumpOnOutOfMemoryError
android.useAndroidX=true
android.enableJetifier=true

# Disable Kotlin incremental compilation to avoid cache errors
kotlin.incremental=false

# Ignore JVM target validation (needed for plugin conflicts)
kotlin.jvm.target.validation.mode=IGNORE

# Flutter template defaults
android.newDsl=false
android.builtInKotlin=false
org.gradle.caching=false
android.uniquePackageNames=false


