// ignore_for_file: prefer_const_constructors, depend_on_referenced_packages

import 'dart:io';
import 'package:drift/drift.dart';
import 'package:drift/native.dart';
import 'package:path_provider/path_provider.dart';
import 'package:path/path.dart' as p;

import '../../core/utils/logger.dart';

part 'database.g.dart'; // Generated by build_runner

// TABLE DEFINITIONS
/// Local scans table — mirrors server schema plus sync state
@DataClassName('LocalScan')
class LocalScans extends Table {
  TextColumn get id => text()(); // Client-side UUID (primary key)
  TextColumn get serverId => text().nullable()(); // Server UUID after sync
  TextColumn get userId => text()(); // Owner user ID
  
  // Prediction results
  TextColumn get predictedClass => text()(); // 'defect', 'longberry', 'peaberry', 'premium'
  RealColumn get confidence => real()();
  
  // Full probability distribution
  RealColumn get probabilityDefect => real()();
  RealColumn get probabilityLongberry => real()();
  RealColumn get probabilityPeaberry => real()();
  RealColumn get probabilityPremium => real()();
  
  // Flags and metadata
  BoolColumn get isOod => boolean().withDefault(const Constant(false))();
  TextColumn get imageLocalPath => text().nullable()();
  TextColumn get imageUrl => text().nullable()(); // Cloud URL after upload
  TextColumn get notes => text().nullable()();
  
  // Timestamps
  DateTimeColumn get createdAt => dateTime()();
  DateTimeColumn get syncedAt => dateTime().nullable()();
  
  // Sync state tracking
  TextColumn get syncState => text().withDefault(const Constant('pending'))(); // 'pending', 'synced', 'failed'
  
  @override
  Set<Column> get primaryKey => {id};
}

/// Sync outbox table — tracks pending operations
@DataClassName('OutboxEntry')
class SyncOutbox extends Table {
  IntColumn get id => integer().autoIncrement()();
  TextColumn get scanId => text()(); // References LocalScans.id
  TextColumn get operation => text()(); // 'insert', 'update', 'delete'
  DateTimeColumn get createdAt => dateTime()();
  IntColumn get attemptCount => integer().withDefault(const Constant(0))();
  TextColumn get lastError => text().nullable()();
  DateTimeColumn get lastAttemptAt => dateTime().nullable()();
}

// DATABASE
@DriftDatabase(tables: [LocalScans, SyncOutbox])
class AppDatabase extends _$AppDatabase {
  AppDatabase() : super(_openConnection());

  @override
  int get schemaVersion => 1;

  @override
  MigrationStrategy get migration => MigrationStrategy(
        // Called when the DB is opened for the first time (fresh install).
        onCreate: (m) => m.createAll(),
        onUpgrade: (m, from, to) async {
          AppLogger.e(
            'DB schema upgraded $from → $to with no migration steps defined. '
            'Drop and recreate was called.',
          );
          await m.recreateAllViews();
        },
      );

  // SCANS QUERIES

  // Get all scans for a user, sorted by creation date (newest first)
  Future<List<LocalScan>> getAllScans(String userId) {
    return (select(localScans)
          ..where((t) => t.userId.equals(userId))
          ..orderBy([(t) => OrderingTerm.desc(t.createdAt)]))
        .get();
  }

  // Get a single scan by client ID
  Future<LocalScan?> getScanById(String scanId) {
    return (select(localScans)..where((t) => t.id.equals(scanId)))
        .getSingleOrNull();
  }

  // Get scans by predicted class
  Future<List<LocalScan>> getScansByClass(String userId, String predictedClass) {
    return (select(localScans)
          ..where((t) =>
              t.userId.equals(userId) &
              t.predictedClass.equals(predictedClass))
          ..orderBy([(t) => OrderingTerm.desc(t.createdAt)]))
        .get();
  }

  // Get recent scans (limit N)
  Future<List<LocalScan>> getRecentScans(String userId, {int limit = 10}) {
    return (select(localScans)
          ..where((t) => t.userId.equals(userId))
          ..orderBy([(t) => OrderingTerm.desc(t.createdAt)])
          ..limit(limit))
        .get();
  }

  // Count total scans for a user
  Future<int> countScans(String userId) async {
    final count = localScans.id.count();
    final query = selectOnly(localScans)
      ..addColumns([count])
      ..where(localScans.userId.equals(userId));
    final result = await query.getSingle();
    return result.read(count) ?? 0;
  }

  // Insert a new scan
  Future<int> insertScan(LocalScansCompanion scan) {
    return into(localScans).insert(scan);
  }

  // Update an existing scan
  Future<bool> updateScan(LocalScan scan) {
    return update(localScans).replace(scan);
  }

  // Update scan notes
  Future<int> updateScanNotes(String scanId, String notes) {
    return (update(localScans)..where((t) => t.id.equals(scanId)))
        .write(LocalScansCompanion(notes: Value(notes)));
  }

  // Mark scan as synced
  Future<int> markScanSynced(String scanId, String serverId) {
    return (update(localScans)..where((t) => t.id.equals(scanId))).write(
      LocalScansCompanion(
        serverId: Value(serverId),
        syncedAt: Value(DateTime.now()),
        syncState: const Value('synced'),
      ),
    );
  }

  // Mark scan sync as failed
  Future<int> markScanFailed(String scanId) {
    return (update(localScans)..where((t) => t.id.equals(scanId)))
        .write(const LocalScansCompanion(syncState: Value('failed')));
  }

  // Delete a scan
  Future<int> deleteScan(String scanId) {
    return (delete(localScans)..where((t) => t.id.equals(scanId))).go();
  }

  // Delete all scans for a user (on sign out with clear data)
  Future<int> deleteAllScans(String userId) {
    return (delete(localScans)..where((t) => t.userId.equals(userId))).go();
  }

  // SYNC OUTBOX QUERIES

  // Get all pending outbox entries
  Future<List<OutboxEntry>> getPendingOutbox() {
    return (select(syncOutbox)
          ..orderBy([(t) => OrderingTerm.asc(t.createdAt)]))
        .get();
  }

  // Add an entry to the outbox
  Future<int> addToOutbox(SyncOutboxCompanion entry) {
    return into(syncOutbox).insert(entry);
  }

  // Remove an outbox entry after successful sync
  Future<int> removeFromOutbox(int outboxId) {
    return (delete(syncOutbox)..where((t) => t.id.equals(outboxId))).go();
  }

  Future<int> updateOutboxFailure(
    int outboxId,
    int currentAttemptCount,
    String error,
  ) {
    return (update(syncOutbox)..where((t) => t.id.equals(outboxId))).write(
      SyncOutboxCompanion(
        attemptCount: Value(currentAttemptCount + 1), // ← correctly increments
        lastError: Value(error),
        lastAttemptAt: Value(DateTime.now()),
      ),
    );
  }

  // Clear all outbox entries (nuclear option, with confirmation)
  Future<int> clearOutbox() {
    return delete(syncOutbox).go();
  }

  // BATCH OPERATIONS

  // Insert multiple scans from server (during sync pull)
  Future<void> insertScansFromServer(List<LocalScansCompanion> scans) async {
    await batch((batch) {
      batch.insertAll(localScans, scans, mode: InsertMode.insertOrReplace);
    });
  }

  // Merge remote scans with local (server wins for conflicts)
  Future<void> mergeRemoteScans(List<LocalScansCompanion> remoteScans) async {
    await batch((batch) {
      batch.insertAll(localScans, remoteScans, mode: InsertMode.insertOrReplace);
    });
  }
}

// CONNECTION
LazyDatabase _openConnection() {
  return LazyDatabase(() async {
    final dbFolder = await getApplicationDocumentsDirectory();
    final file = File(p.join(dbFolder.path, 'buna_lens.db'));
    return NativeDatabase(file);
  });
}
